# num1=10
# num2=0
# res=num1/num2
# print(res)

# a=[1,2,3,4]
# print(a[5])
# print('completed')

# try:
# #code that might throw error
# except:
# #code to run when exception occurs

# try:
#     num1=int(input('Enter  the first number: '))
#     num2=int(input('Enter  the second number: '))
#     result=num1/num2
#     print(result)
# except:
#     print('Invalid number,try again')

# print('Execution is completed')


# try:
#     num1=int(input('Enter  the first number: '))
#     num2=int(input('Enter  the second number: '))
#     result=num1/num2
#     print(result)
# except:
#     print('Invalid number,try again')

# finally:
#     print('All Good')
# print('Execution is completed')



# x=5
# y=0
# #operations only give inside try
# try:
#     # assert x>6
#     # print(m)
#     # print(x/y)
#     #we can only do each operations separately inside try
# except NameError as ne:
#     print(ne)
#     print('Name Error!!!!!!!')
# except ZeroDivisionError as ze:
#     print(ze)
#     print('Zero Division Error!!!!!!!!')
# except:
#     print('Error occured!!!!!')
# #this part occur if any other error other than given will occur
# finally:
#     print('Hii Python!!!!!')

# x=int(input('inter the number:'))
# if type(x) is not int:
#     raise Exception
# else:
#     print(x)

# x=int(input('inter the number:'))
# if x>10:
#     raise Exception
# else:
#     print(x)

# randomlist=['a',0,2]
# for random in randomlist:
#     try:
#         print('Random number is:',random)
#         x=1/int(random)
#     except:
#         print(' somethin wrong')
#         print('try again')
#         print()
# print('The result is:',x)


# try:
#     a=34
#     b=56
#     assert a==b
# except:
#     raise 

# try:
#     a=34
#     b=56
#     assert a==b
# except AssertionError as g:
#     print(g)
#     print('oops!!!!,assertion error occur ')
    

# try:
#     a=34
#     b=56
#     assert a==b
# except:
#     raise Exception







